### ISSUE TITLE
error starting GUI

### ISSUE THREAD

**Issue by OctAg0nO** [AIIX/Mycroft-AI-Gnome-Shell-Extension#1]
im trying to use the extension, im geting this error:
NameError: name 'traceback' is not defined

im using a raspberry pi 3 on ubuntu mate distro.

**Comment by AIIX** [comment]
from the terminal run: pip install traceback, if traceback is installed, open guignome.py  try import traceback. If error is not solved please post your gnome shell version and output of journalctl /usr/bin/gnome-shell -f -o cat

**Comment by OctAg0nO** [comment]
GNOME Shell 3.18.5

running 'pip install traceback' give me this error:
Collecting traceback
  Could not find a version that satisfies the requirement traceback (from versions: )
No matching distribution found for traceback

i run 'apt-get install python-traceback2'
python-traceback2 is already the newest version (1.4.0-3).

import traceback on guignome.py now get this error: 

Traceback (most recent call last):
  File "/home/octagono/mycroft-core-master/mycroft/client/gui/guignome.py", line 92, in <module>
    object = bus.get_object("org.gnome.Shell","/com/mycroftaignome/MycroftGnomeResult")
  File "/home/octagono/.virtualenvs/mycroft/local/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/home/octagono/.virtualenvs/mycroft/local/lib/python2.7/site-packages/dbus/proxies.py", line 248, in **init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/home/octagono/.virtualenvs/mycroft/local/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/home/octagono/.virtualenvs/mycroft/local/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/home/octagono/.virtualenvs/mycroft/local/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell was not provided by any .service files
Error

**Comment by AIIX** [comment]
is the extension enabled ? open d-feet -> under session bus -> search for org.gnome.shell if found open and search for  /com/mycroftaignome/MycroftGnomeResult in object path is it there ?

**Comment by OctAg0nO** [comment]
'mycroftaignome@aix.com' is already enabled.

when open d-feet ->  session bus -> org.gnome.shell 
have 3 results there:
org.gnome.shell.CalendarServer
org.gnome.shell.HotPlugSniffer
org.gnome.shell.PortalHelper

**Comment by AIIX** [comment]
run journalctl /usr/bin/gnome-shell -f -o cat, alt+f2, type 'r', start mycroft service..type anything in the entry query box,  post the full output of  journalctl /usr/bin/gnome-shell -f -o cat.

**Comment by AIIX** [comment]
does d-feet look similar to this:  
![d-feet for org gnome shell](https://cloud.githubusercontent.com/assets/19663666/16372403/7c4ea4cc-3c8b-11e6-8787-7ad9886a3019.png)

**Comment by OctAg0nO** [comment]
yes, but only have this 3 results there:
org.gnome.shell.CalendarServer
org.gnome.shell.HotPlugSniffer
org.gnome.shell.PortalHelper

not org.gnome.shell

**Comment by AIIX** [comment]
the extension is dependent on org.gnome.shell service in session bus running in dbus which is missing. I am not sure about how your ubuntu mate distro is configured with gnome 3, try updating your gnome shell to version 3.20.
