### ISSUE TITLE
MycroftService*.sh not showing up on install

### ISSUE THREAD

**Issue by ebeyer** [AIIX/Mycroft-AI-Gnome-Shell-Extension#2]
(fully admitting the bug may be between the keyboard and chair..)

I followed the install instructions up to step 3 -> 1, where one sets permissions for the MycroftServiceStart.sh, *Gui.sh, *Stop.sh but I do not see these files in my ~/.local/share/gnome-shell/extensions/ folder.  Rather I just see a Mycroft-AI-Gnome-Shell-Extension-master folder in that directory.  Where/how am I messing up and how might I troubleshoot this?

Also, step 2 -> 7 seems to have an extra 'o' in 'gobject'.

Thanks in advance.
EB

**Comment by AIIX** [comment]
Released version 0.1.2, if using ubuntu based distro the installation can be done through installextension.sh file. The readme has also been updated please check the new manual installation method steps. Let me know if issue is resolved

**Comment by ebeyer** [comment]
The script choked when it couldn't find a couple directories that didn't exist, but I created them manually and it was able to finish without any errors.  It seems to be installed now.  Thanks!
