### ISSUE TITLE
Extension incompatible with 3.14, readme doesn't specify versions 

### ISSUE THREAD

**Issue by jlnxr** [AIIX/Mycroft-AI-Gnome-Shell-Extension#3]
The extension is incompatible with Gnome 3.14. I am personally of the opinion that gnome extensions should try to support the Gnome version on the current Debian stable (as most do), considering the size and importance of the distribution, but if this isn't possible then at the very least the readme should specify what versions it is in fact compatible with.

**Comment by AIIX** [comment]
I haven't tested the extension on Gnome 3.14 and it might not even be compatible as Dbus implementation might need a different mark up for 3.14.
