### ISSUE TITLE
Open Extension when text is processing

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [AIIX/Mycroft-AI-Gnome-Shell-Extension#4]
This is more a feature than anything else.

I'd like that when Mycroft starts processing a sentence, the extension would open to let the user know Mycroft is doing something.

Example:
1. I say "Mycroft what day is it?"
2. Mycroft extension pops up with a loading animation.
3. Mycroft starts speaking it's reply
4. Mycroft extension shows what Mycroft is saying
5. After 10 seconds the extension is dismissed.

**Comment by AIIX** [comment]
This is somewhat planned in the upcoming version, I still have to work out how to implement this as writing a whole new notification system isn't something feasible. It might take a while before the next release as it is a full rewrite of the current extension and I am still working around a native communication channel with Mycroft without the use of external dependencies.

**Comment by AIIX** [comment]
Added a workaround - Displays reply in notification when mycroft replies.
